name: Asset release YML

on:
  workflow_dispatch:
  workflow_call:
  push:
    release:
      types: [published]

jobs:
  build:
    name: Asset release JOB
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Generate ZIP file
        run: pwd && ls

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: asset-release-zip-test.zip
